### PR TITLE
Add gromox-cleanup.sh script

### PR DESCRIPTION
**Pull request by deajan**
Purpose of this PR: Keep gromox folders clean

While playing with gromox, I wrote a prometheus exporter [here](https://github.com/netinvent/grommunio_exporter) after which I noticed that some mailboxes were quite huge, even when the ondisk maidir was twice as small.

Discussing with @WalterHof and @crpb, they suggested to run various cleanups.
I was wondering why that wasn't "standard" for Grommunio, so here's a script that perhaps should be added by default to Grommunio's setup via a systemd timer / or even as fs-hook/thaw for VM environments.

Currently tested on two Grommunio servers running gromox 2.37.

Thanks for considering this.

### CODE REVIEW

**Comment by WalterHof** [comment]
Do not write to a log file (/var/log/${SCRIPT_NAME}.log). Write to systemd logging instead,

**Comment by crpb** [comment]
> Write to systemd logging instead,

ahh right. and with the .service you can just echo you to stdout and it will show up in the journal under --unit grommunio-cleanup  or however it might be called in the end.
And for different levels `logger`/`systemd-cat` -p err/info/...

**Comment by deajan** [comment]
Pull request updated as per your suggestions. New script has been tested again.
@crpb Note that I have changed the timer to make it run everyday at 2am.

**Comment by jengelh** [comment]
>for maildir in $(grommunio-admin user query maildir | awk '{if ($1~gromox_mail) {print $1}}' gromox="${GROMOX_MAILDIR_PATH}"); do

Ugh, this is ugly. We have `for-all-users echo-username` since gromox-2.35-45-g34e58d9f2 .

And now, since gromox-2.38-17-gdde284b64 , it also knows `for-all-users \( purge-softdelete ... \) \( purge-datafiles \)`, so the loop can also go away. ;-)

**Comment by crpb** [comment]
> We have `for-all-users echo-username`

Which will print out groups aswell which don't have any maildirs and therefore will give me an error on use or not? Same with the "admin" user.
These **ugly** hacks are there for a reason or we just need to have some guidance on how to do it better as i can't seem to get it going here.
```
grom-test-2:~ # rpm -q gromox
gromox-2.38.17.gdde284b-lp156.20.1.x86_64
grom-test-2:~ # gromox-mbop for-all-users \( purge-datafiles \)
purge-datafiles: the operation failed
grom-test-2:~ # gromox-mbop for-all-users purge-datafiles
purge-datafiles: the operation failed
grom-test-2:~ # man gromox-mbop
grom-test-2:~ # gromox-mbop for-all-users -j 10 purge-datafiles
purge-datafiles: the operation failed
grom-test-2:~ # gromox-mbop for-all-users echo-username |wc -l
25
```

**Comment by WalterHof** [comment]
Hi,

danke, schon gelesen, werde ich in den Weihnachtsfeiertagen umbauen.


WH


    --------------------Ursprüngliche Nachricht--------------------
    Von: crpb ***@***.***>
    Gesendet: Samstag 14. Dezember 2024 1:52
    An: grommunio/gromox ***@***.***>
    CC: Walter Hofstädtler ***@***.***>; Mention
    ***@***.***>
    Betreff: Re: [grommunio/gromox] Add gromox-cleanup.sh script (PR #111)

   

        We have for-all-users echo-username

    Which will print out groups aswell which don't have any maildirs and
    therefore will give me an error on use or not? Same with the "admin" user.
    These ugly hacks are there for a reason or we just need to have some
    guidance on how to do it better as i can't seem to get it going here.

    grom-test-2:~ # rpm -q gromox
    gromox-2.38.17.gdde284b-lp156.20.1.x86_64
    grom-test-2:~ # gromox-mbop for-all-users \( purge-datafiles \)
    purge-datafiles: the operation failed
    grom-test-2:~ # gromox-mbop for-all-users purge-datafiles
    purge-datafiles: the operation failed
    grom-test-2:~ # man gromox-mbop
    grom-test-2:~ # gromox-mbop for-all-users -j 10 purge-datafiles
    purge-datafiles: the operation failed
    grom-test-2:~ # gromox-mbop for-all-users echo-username |wc -l
    25

    —
    Reply to this email directly, view it on GitHub, or unsubscribe.
    You are receiving this because you were mentioned.Message ID: <grommunio/
    ***@***.***>

**Comment by deajan** [comment]
I'll remove my ugly hacks in favor of the recent commands somewhere around this weekend and update the PR ;)

**Comment by crpb** [comment]
Oh and not only groups but contacts aswell what will look a bit confusing on usage 🙈 
```
armitage:~ # ./scripts/tools/g_user_count.sh

Count grommunio Users / Mailboxes
V.: 1.1, (c) 2023 by Walter@Hofstaedtler.com and cb

Counting items please wait ...

  52 users / mailboxes to be licensed, includes 0 suspended users, rooms and equipment,
  21 shared mailboxes (free),
  61 groups / distribution lists (free),
  73 mailboxes total.
 138 contacts.

armitage:~ # gromox-mbop for-all-users echo-username |wc -l
273
armitage:~ # gromox-mbop for-all-users purge-datafiles
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
purge-datafiles: the operation failed
armitage:~ #
```

**Comment by jengelh** [comment]
new iteration verbs added, cf. gromox-2.38-33-gb00c21f49
unit tryout: refs/heads/cleaner
Unit still needs extra conditions and only makes sense to run when gromox-http is operating.

**Comment by deajan** [comment]
So basically this script is not needed anymore, closing in favor of #117.

**Pull request closed without merging**
