### PR TITLE
define process names for syslog

### PR DESCRIPTION
**Pull request by midasi**
When using syslog, the process name is currently empty. To fix this, the syslog ident has to be set explicitly.

### CODE REVIEW

**Comment by jengelh** [comment]
Which libc and syslog implementations do you have running?

**Comment by midasi** [comment]
We use musl libc on Alpine Linux

**Comment by jengelh** [comment]
but with systemd-journald or..?

**Comment by midasi** [comment]
No, with traditional syslog files. Alpine doesn't use systemd or journald

**Pull request merged**
